.TH MYSTRLEN 3 "2025-09-23" "libmyutils" "Library Functions"
.SH NAME
mystrlen \- return length of a NUL-terminated string
.SH SYNOPSIS
#include "mystrfunctions.h"

int mystrlen(const char *s);
.SH DESCRIPTION
mystrlen counts the number of bytes in the NUL-terminated string pointed to by s, not
including the terminating NUL ('\0') character. It is analogous to the standard C strlen
but returns an int.

If s is NULL, the behaviour is undefined (caller must ensure a valid pointer).
.SH RETURN VALUE
On success returns the number of characters in s (>= 0). No global state is modified.
.SH EXAMPLE
.B
char *s = "hello";
int len = mystrlen(s);  /* len == 5 */
.SH AUTHOR
Bisma Munir <bsdsf23m005@pucit.edu.pk>


