.TH MYSTRNCPY 3 "2025-09-23" "libmyutils" "Library Functions"
.SH NAME
mystrncpy \- copy up to n characters from src into dest
.SH SYNOPSIS
#include "mystrfunctions.h"

int mystrncpy(char *dest, const char *src, int n);
.SH DESCRIPTION
mystrncpy copies at most n bytes from src into dest. The function ensures the
destination string is NUL-terminated if there is room: if src length < n the terminating
NUL is copied; if src length >= n then dest will contain the first n bytes and result
is not NUL-terminated by this function (caller must account for that).

The caller is responsible for providing a dest buffer of adequate size.
.SH RETURN VALUE
Returns the number of bytes written into dest. If fewer than n bytes are copied due to
encountering the terminating NUL, the returned value will be <= n.
.SH EXAMPLE
.B
char buf[10];
int written = mystrncpy(buf, "hello", 10); /* written==5, buf=="hello" */
.SH AUTHOR
Bisma Munir <bsdsf23m005@pucit.edu.pk>


