.TH STATIC-CLIENT 1 "2025-09-23" "libmyutils" "User Commands"
.SH NAME
static-client \- demo program linked against the static library libmyutils.a
.SH SYNOPSIS
.B static-client
[\fBoptions\fR] [\fIfiles...\fR]
.SH DESCRIPTION
static-client is built using a statically linked version of the project library
(libmyutils.a). It demonstrates that functions are included in the binary and do not
require external shared objects at runtime.
.SH OPTIONS
None standardized.
.SH EXAMPLES
static-client file.txt
.SH AUTHOR
Bisma Munir <bsdsf23m005@pucit.edu.pk>


